### ISSUE TITLE
apoi... ai field language.. si returnezi un string fix... DE CE?!?!?

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#10]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex2_3/Programmer.java#L11

**Comment by cezarhre** [comment]
Am reparat punind la parametru
