### ISSUE TITLE
asta trebuie sa dispara... Un employee fara nume, adresa, etc... nu trebuie sa poata fi creat

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#13]
https://github.com/cezarhre/curs9homework.classes/blob/210462d07f74aa4b01dcab2100997a9078255d3e/src/ro/fasttrackit/curs9/homework/ex2_3/Employee.java#L24

**Comment by cezarhre** [comment]
Am refacut si am trimis
