### ISSUE TITLE
inca o data.. varsta ta nu e de cand te-ai nascut pana te-ai angajat. Ci ... pana azi...

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#15]
https://github.com/cezarhre/curs9homework.classes/blob/a791034dce0c0c82774a3907c6d54d3d346dd6fc/src/ro/fasttrackit/curs9/homework/ex2_3/Employee.java#L51

**Comment by cezarhre** [comment]
Stiu. In main am facut diferenta...

**Comment by cezarhre** [comment]
Am vrut sa fac diferenta intre doua date pe care le introduc manual...
