### ISSUE TITLE
nu e frumos.. parintele aproape ca nu are state.. fa-i un constructor asa cum ziceam la issueul precendent, sau foloseste ala care seteaza stateul serios.

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#3]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex1/Cosmetics.java#L8

**Comment by cezarhre** [comment]
Am refacut
