### ISSUE TITLE
cam useless constructorul ala... nu poti trimite nimic din exterior, te obliga sa folosesti setter... urat.

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#4]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex1/Electronics.java#L10

**Comment by cezarhre** [comment]
Am refacut
