### ISSUE TITLE
mda.. constructorul asta creaza un frigider care are doar temperatura si lasa nesetate toate fieldurile parintilor... :(

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#5]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex1/Fridge.java#L7

**Comment by cezarhre** [comment]
in cerinta era doar temperatura. Nu stiam ca trebuie sa dau si alte caracteristici din product.
Refac...
