### ISSUE TITLE
da ce-i asta? creem metode care stiu returna o singura valoare? Fa-i un field frumos si e dinamic... ca doar nu ne-am nascut toti in 1999... Atentie la cum poti folosi obiectele tale... Daca par inutile... probabil ai gresit ceva. Fa state

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#7]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex2_3/Employee.java#L21

**Comment by cezarhre** [comment]
Nu am stiut altfel cum sa fac astfel incit in Programmer sa returneze alta pozitie prin Override...

**Comment by cezarhre** [comment]
Am refacut...
