### ISSUE TITLE
felicitari pt folosirea Period.between, dar nu ai atatia ani de cand te-ai nascut pana te-ai angajat... alta e referinta pt cati ani ai :)

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs9homework.classes#8]
https://github.com/cezarhre/curs9homework.classes/blob/e0cdd1c3732a0af9910e24b10e04a2ccf8fa2bcc/src/ro/fasttrackit/curs9/homework/Ex2_3/Employee.java#L41

**Comment by cezarhre** [comment]
Intentionat am facut asa deoarece am considerat ca este virsta de la angajare si nu in momentul prezent (adica LocalDate.now)
